### ISSUE TITLE
AttributeError: 'BertTokenizer' object has no attribute 'tokens_trie'

### ISSUE THREAD

**Issue by SyedA5688** [yulong-XJTU/SimVLM#3]
I am getting an error related to the ChineseTokenizer:
"AttributeError: 'BertTokenizer' object has no attribute 'tokens_trie'"

I believe this is related to my version of transformers installed in my system. Currently, I have transformers version 4.21.2 installed, and I get this error when I try to tokenize text input during training. I was wondering if you could provide a requirements file of your environment, or tell what version of transformers do you have installed which relates to the tokenizer. Thank you in advance!

**Comment by yulong-XJTU** [comment]
the version of  transformers in my env is  4.6.1  .  Maybe your can reload the tokenizer from web according to your version of package. 
 ``` tokenizer=BertTokenizer.from_pretrained('bert-base-chinese')
    torch.save(tokenzier,path)
```

**Comment by SyedA5688** [comment]
I was able to load the bert-base-uncased tokenizer after some modifications to the tokenizer file. Thanks!
